### ISSUE TITLE
[🐛] Error al votar en polls

### ISSUE THREAD

**Issue by arturoluona** [codigoencasa/builderbot#1085]
### ¿Que versión estas usando?

v1

### ¿Sobre que afecta?

Otro

### Describe tu problema

Problema:
![image](https://github.com/user-attachments/assets/78da66c4-3a89-4bef-97c3-7c27491380a0)

Pasos a reproducir:
Crear un poll y votar repetidamente en varios values

**Comment by andresayac** [comment]
Voy a recrearlo para ver lo que comentas. ¿Puedes especificar la versión que utilizas? @arturoluona

**Comment by andresayac** [comment]
> Voy a recrearlo para ver lo que comentas. ¿Puedes especificar la versión que utilizas? @arturoluona


https://github.com/user-attachments/assets/a54c16c4-da1f-4427-931b-37c9e0c3b7b3

**Comment by arturoluona** [comment]
@andresayac
Estoy usando la version:

`"@Builderbot/bot": "1.1.5",`
`"@Builderbot/provider-baileys": "1.1.5",`


He estado viendo más a fondo y parece que a veces `baileys` no captura el id del voto y lanza el error

Es difícil de replicar el error, hay que durar bastante tiempo intentando replicarlo

Tengo el bot en producción, lo que he hecho por ahora es capturar el error para que no se reinicie el servidor y no se rompa la conversación

El bot consiste en un flujo de polls donde el usuario debe responder cosas específicas definidas en el poll, por esto está más propenso a capturar este error

PD: hay aproximadamente de 30 a 40 personas interactuando con el bot al día

![image](https://github.com/user-attachments/assets/777de5b0-97b0-4f85-bc72-a3fb2cafde6c)

**Comment by andresayac** [comment]
> > Voy a recrearlo para ver lo que comentas. ¿Puedes especificar la versión que utilizas? @arturoluona
> 
> @andresayac Estoy usando la version:
> 
> `"@Builderbot/bot": "1.1.5",` `"@Builderbot/provider-baileys": "1.1.5",`
> 
> He estado viendo más a fondo y parece que a veces `baileys` no captura el id del voto y lanza el error
> 
> Es difícil de replicar el error, hay que durar bastante tiempo intentando replicarlo
> 
> Tengo el bot en producción, lo que he hecho por ahora es capturar el error para que no se reinicie el servidor y no se rompa la conversación
> 
> El bot consiste en un flujo de polls donde el usuario debe responder cosas específicas definidas en el poll, por esto está más propenso a capturar este error
> 
> PD: hay aproximadamente de 30 a 40 personas interactuando con el bot al día
> 
> ![image](https://private-user-images.githubusercontent.com/56488686/350920550-777de5b0-97b0-4f85-bc72-a3fb2cafde6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NDE2NzEsIm5iZiI6MTcyMTc0MTM3MSwicGF0aCI6Ii81NjQ4ODY4Ni8zNTA5MjA1NTAtNzc3ZGU1YjAtOTdiMC00Zjg1LWJjNzItYTNmYjJjYWZkZTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDEzMjkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZDhkZmI4OWFiNzlhYzIyZTg2NjBlN2QxNmViNzgyZTVlZWMyNTUyN2NlYWVmYjNhYmY4ZTdhNmM2ZDc4MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WzRJ6-xWWDbgWnrw74-re9agc130Jnsfl-ugqqtZhaI)

en base a esto si se debe modificar voy a generar un cambio y no notificate por aqui

**Comment by leifermendez** [comment]
@arturoluona  @andresayac  gracias por comentar este issue puedes probar la version `1.2.2-alpha.0` tiene implementado esta mejora
