### ISSUE TITLE
gotoFlow falla en version mysql [🐛]

### ISSUE THREAD

**Issue by aleangelico** [codigoencasa/builderbot#1090]
### ¿Que versión estas usando?

v1

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Este codigo funciona con el paquete starter "base-baileys-json" pero falla con "base-baileys-mysql". 

```
const { createBot, createProvider, createFlow, addKeyword, EVENTS } = require('@bot-whatsapp/bot')

const BaileysProvider = require('@bot-whatsapp/provider/baileys')
const JsonFileAdapter = require('@bot-whatsapp/database/json')


let plato;

const flowMenu = addKeyword(['menu']).
    addAnswer('Aca tienes el menu',
    null,
    async (ctx, {flowDynamic})=> {
        await flowDynamic("SOPA")
    })
    .addAnswer('Ingresa el plato, FIN  para terminar', {capture: true},  
        async (ctx, {flowDynamic, gotoFlow}) => {
        plato = ctx.body;
        if (plato !== 'SOPA') {            
            return gotoFlow(flowNoExistePlato);
        } else {            
            await flowDynamic(`Elegiste *${plato}*`)
            return gotoFlow(flowCantidadDePlatos);
        }

});


const flowNoExistePlato = addKeyword(EVENTS.ACTION)
.addAnswer("No te he entendido!", null, async (_, { gotoFlow }) => {
    return gotoFlow(flowMenu);
  });


const flowCantidadDePlatos = addKeyword(EVENTS.ACTION)
.addAnswer("Cuantos querés?", null, async (_, { gotoFlow }) => {
    return gotoFlow(flowMenu);
});



const main = async () => {
    const adapterDB = new JsonFileAdapter()
    const adapterFlow = createFlow([flowNoExistePlato, flowCantidadDePlatos, flowMenu])
    const adapterProvider = createProvider(BaileysProvider)

    createBot({
        flow: adapterFlow,
        provider: adapterProvider,
        database: adapterDB,
    })
}

main()
```

El funcionamiento esperado es que si el usuario escribe "SOPA", le pregunte "cuantos queres" y luego vuelva al menu de pedido. Si escribe algo distinto de "SOPA", entonces muestra "No te he entendido". 

Esto funciona bien con el starter "base-baileys-json" .

Si se usa "base-baileys-mysql" cuando va al otro flujo con ```gotoFlow()```,  luego el ```return gotoFlow(flowMenu);``` ya no regresa al ```flowMenu```

**Comment by leifermendez** [comment]
Buenas pruba actualizando a builderbot te dejo la guia https://www.builderbot.app/en/tutorials/migrate-to-builderbot

**Comment by aleangelico** [comment]
> Buenas pruba actualizando a builderbot te dejo la guia https://www.builderbot.app/en/tutorials/migrate-to-builderbot

gracias, voy a probar, pero es gratis? o solo la beta es gratis?

**Comment by aleangelico** [comment]
> Buenas pruba actualizando a builderbot te dejo la guia https://www.builderbot.app/en/tutorials/migrate-to-builderbot

así lo haré, gracias
