### ISSUE TITLE
[🐬] Se puede usar el bot sin necesidad de usar un puerto y ejecutar httpServer?

### ISSUE THREAD

**Issue by alexandrecastillo** [codigoencasa/builderbot#1100]
### ¿Cual proveedor usaste?

bailey

### ¿Cual base de datos usaste?

memory

### Conclusion de la prueba

buena

### Describe tu caso

Hola mi duda es si se puede usar el bot sin necesidad de usar un puerto y ejecutar httpServer?

```
const { httpServer } = await createBot({
        flow: adapterFlow,
        provider: adapterProvider,
        database: adapterDB,
    })

    httpServer(+PORT) 
```

Me gustaría integrarlo en un proyecto y usarlo como una librería dentro de ella, sin usar el puerto y los métodos http.
Veo que en la librería WhiskeySockets/Baileys no define ni usa un puerto.

Gracias por el gran trabajo.

**Comment by andresruizdev** [comment]
Hola. No, por defecto builderbot hace uso de un puerto para poder iniciarse. [Puedes verlo acá](https://github.com/codigoencasa/builderbot/blob/27d700d6432f7d592399a499754b7abb94f68c31/packages/bot/src/core/coreClass.ts#L718)
