### ISSUE TITLE
[🐬]Events dentro de flows

### ISSUE THREAD

**Issue by maudicito** [codigoencasa/builderbot#1106]
### ¿Cual proveedor usaste?

meta

### ¿Cual base de datos usaste?

memory

### Conclusion de la prueba

muy buena

### Describe tu caso

Tengo un menu dentro de mi bot donde la ultima opción es hablar con una persona, misma donde quiero colocar mi webhook con chatwoot, y para esto intente escuchar los eventos "message" y "send_message" dentro del flujo que tengo modularizado, siendo no exitoso.

Donde mi duda es la siguiente:

Se puede escuchar eventos fuera del app.js, es decir desde cualquier flujo que tenga en distintos .js ? o que alternativa puedo utilizar, para esto estoy usando MetaProvider

![image](https://github.com/user-attachments/assets/397a081b-7d41-447c-bed9-f41c383b7f36)

**Comment by DavidKingV** [comment]
Si se puede:
https://youtu.be/dNgGfoSgq2E?si=dbqHAwTSElIj_wqe&t=3939
