### ISSUE TITLE
[🐛] Idle solo funciona en un solo flujo en los demas no lo hace

### ISSUE THREAD

**Issue by Fanger53** [codigoencasa/builderbot#1108]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

he usado Idle en un flujo, pero al tratar de usarlo de nuevo en otro flujo no funciona.
![image](https://github.com/user-attachments/assets/23a65760-43bc-45bb-8174-1b8809551127)

**Comment by DavidKingV** [comment]
Revisa que este llamando correctamente a tu archivo donde tengas el código del idle

`import { start, reset, stop } from '../src/utils/idle'`

**Comment by Fanger53** [comment]
gracias con eso encontré una solución al issue que tenia
