### ISSUE TITLE
[🐛]Comprobando requerimientos └  Ups! 🙄 algo no va bien. Revisa los requerimientos minimos en la documentacion

### ISSUE THREAD

**Issue by supnet45** [codigoencasa/builderbot#1111]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

Intento instalar, pero me informa:

 Vamos a crear un  Chatbot  ✨
│
◇  ¿Quieres continuar?
│  Yes
│
◇  ¿Cuál proveedor de whatsapp quieres utilizar?
│  Baileys
│
◇  ¿Cuál base de datos quieres utilizar?
│  Memory
│
○  Comprobando requerimientos
└  Ups! 🙄 algo no va bien.
Revisa los requerimientos minimos en la documentacion

**Comment by DavidKingV** [comment]
Revisa tu versión de nodejs

**Comment by supnet45** [comment]
Hola, tengo la version 23.3 instalada.

**Comment by supnet45** [comment]
Ya resuelto. Muchas gracias.

**Comment by DavidKingV** [comment]
> Ya resuelto. Muchas gracias.

¿que fue?
